# Generated by Django 2.2.6 on 2019-11-15 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20191115_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Name must be greater than 2 characters')])),
                ('picture', models.BinaryField(editable=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='nation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Nation'),
        ),
    ]
